/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_hive_ql_io_orc_JNICall */

#ifndef _Included_org_apache_hadoop_hive_ql_io_orc_JNICall
#define _Included_org_apache_hadoop_hive_ql_io_orc_JNICall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_hive_ql_io_orc_JNICall
 * Method:    SnapInitHashTable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hive_ql_io_orc_JNICall_SnapInitHashTable
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_hive_ql_io_orc_JNICall
 * Method:    SnapBuildHashTable
 * Signature: (ILorg/apache/hadoop/hive/ql/io/orc/ColumnizedDeleteEventRegistry/DeleteRecordKey;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hive_ql_io_orc_JNICall_SnapBuildHashTable
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_apache_hadoop_hive_ql_io_orc_JNICall
 * Method:    SnapReadHashTable
 * Signature: (Lorg/apache/hadoop/hive/ql/exec/vector/VectorizedRowBatch;Ljava/util/BitSet;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hive_ql_io_orc_JNICall_SnapReadHashTable
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_apache_hadoop_hive_ql_io_orc_JNICall
 * Method:    SubSnapReadHashTable
 * Signature: (Ljava/util/BitSet;[J[J[J)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hive_ql_io_orc_JNICall_SubSnapReadHashTable
  (JNIEnv *, jobject, jobject, jlongArray, jlongArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
