/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_hive_ql_io_orc_JNICall */

#ifndef _Included_org_apache_hadoop_hive_ql_io_orc_JNICall
#define _Included_org_apache_hadoop_hive_ql_io_orc_JNICall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_hive_ql_io_orc_JNICall
 * Method:    PrintfakeDeleteDeltas
 * Signature: (Ljava/util/Iterator;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hive_ql_io_orc_JNICall_PrintfakeDeleteDeltas
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_apache_hadoop_hive_ql_io_orc_JNICall
 * Method:    SnapBuildHashTable
 * Signature: (ILorg/apache/hadoop/hive/ql/io/orc/ColumnizedDeleteEventRegistry/DeleteRecordKey;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hive_ql_io_orc_JNICall_SnapBuildHashTable
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
